#workspace:
#  base: /python
#  path: app/

pipeline:
  install:
    image: python
    commands:
    - ls
    - pwd
    - env
    - pip install .
#    - python -m drone_test.app
    - pip install docker-compose
    - docker-compose -h
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock

service:
  cache:
    image: redis
    volumes:
    - /srv/redis:/data