pipeline:
  install:
    image: tiangolo/docker-with-compose
    commands:
    - docker-compose --project-name ${CI_REPO_NAME} -f .docker-compose.yml up --build -d
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock