#workspace:
#  base: /python
#  path: app/

pipeline:
  install:
    image: python
    commands:
    - ls
    - pwd
    - env
    - pip install .
    - pip install docker-compose
    - docker-compose up --force-restart -f .docker/docker-compose.yml --project-name ${CI_REPO_NAME} -d
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock

service:
  cache:
    image: redis
    volumes:
    - /srv/redis:/data