#workspace:
#  base: /python
#  path: app/

pipeline:
  install:
    image: python
    commands:
    - ls
    - pwd
    - env
    - pip install .
    - pip install docker-compose > /dev/null
    - docker-compose --project-name -f .docker/docker-compose.yml ${CI_REPO_NAME} up -d
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock

service:
  cache:
    image: redis
    volumes:
    - /srv/redis:/data